simplemooc/simplemooc/courses/urls.py
from django.conf.urls import url
from simplemooc.courses import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    url(r'^(?P<slug>[\w_-]+)/inscricao/$', views.enrollment, name='enrollment'),
    url(r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$', views.undo_enrollment, name='undo_enrollment'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/$', views.announcements, name='announcements'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', views.show_announcement, name='show_announcement'),
    url(r'^(?P<slug>[\w_-]+)/aulas/$', views.lessons, name='lessons'),
    url(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$', views.lesson, name='lesson'),
    url(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', views.material, name='material'),
]

simplemooc/simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^forum/', include('simplemooc.threads.urls', namespace='threads')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/courses/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from simplemooc.core.mail import send_mail_template



class CourseManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(description__icontains=query)
        )


class Course(models.Model): 
    name = models.CharField('nome', max_length=255)
    slug = models.SlugField('atalho')
    description = models.TextField('descrição simples', blank=True)
    about = models.TextField('sobre o curso', blank=True)
    start_date = models.DateField('data de início', null=True, blank=True)
    image = models.ImageField(
        'imagem', upload_to='courses/images', null=True, blank=True)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)
    objects = CourseManager()

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('courses:details', (), {'slug': self.slug})

    def release_lessons(self):
        today = timezone.now().date()
        return self.lessons.filter(release_date__gte=today)

    class Meta:
        db_table = 'courses'
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'
        ordering = ['name']


class Lesson(models.Model):
    name = models.CharField('nome', max_length=100)
    description = models.TextField('descrição', blank=True)
    number = models.IntegerField('número (ordem)', blank=True, default=0)
    release_date = models.DateField('data de liberação', blank=True, null=True)
    course = models.ForeignKey(Course, verbose_name='curso', related_name='lessons')
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)

    def __str__(self):
        return self.name

    def is_available(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date >= today
        return False

    class Meta:
        verbose_name = 'aula'
        verbose_name_plural = 'aulas'
        ordering = ['number']


class Material(models.Model):
    name = models.CharField('nome', max_length=100)
    embedded = models.TextField('vídeo embedded', blank=True)
    file = models.FileField(
        upload_to='lessons/materials', verbose_name='arquivo',
        blank=True, null=True
    )
    lesson = models.ForeignKey(Lesson, verbose_name='aula', related_name='materials')

    def is_embedded(self):
        return bool(self.embedded)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'material'
        verbose_name_plural = 'materiais'


class Enrollment(models.Model):
    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Cancelado')
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='usuário',
        related_name='enrollments'
    )
    course = models.ForeignKey(
        Course, verbose_name='curso', related_name='enrollments'
    )
    status = models.IntegerField(
        'status', choices=STATUS_CHOICES, default=0, blank=True
    )
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)

    def active(self):
        self.status = 1
        self.save()

    def is_approved(self):
        return self.status == 1

    class Meta:
        verbose_name = 'inscrição'
        verbose_name_plural = 'inscrições'
        unique_together = (('user', 'course'),)


class Announcement(models.Model):
    course = models.ForeignKey(
        Course, verbose_name='curso', related_name='announcements'
    )
    title = models.CharField('título', max_length=100)
    content = models.TextField('conteúdo')
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'anúncio'
        verbose_name_plural = 'anúncios'
        ordering = ['-created_at']


class Comment(models.Model):
    announcement = models.ForeignKey(
        Announcement, verbose_name='anúncio', related_name='comments'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='usuário')
    comment = models.TextField('comentário')
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)

    class Meta:
        verbose_name = 'comentário'
        verbose_name_plural = 'comentários'
        ordering = ['created_at']


def post_save_announcement(instance, created, **kwargs):
    if created:
        subject = instance.title
        template_name = 'courses/announcement-mail.html'
        context = {'announcement': instance}
        enrollments = Enrollment.objects.filter(
            course=instance.course, status=1
        )
        for enrollment in enrollments:
            recipient_list = [enrollment.user.email]
            send_mail_template(subject, template_name, context, recipient_list)


models.signals.post_save.connect(
    post_save_announcement, sender=Announcement,
    dispatch_uid='post_save_announcement'
)

simplemooc/simplemooc/courses/forms.py
from django.core.mail import send_mail
from django.conf import settings
from django import forms
from simplemooc.core.mail import send_mail_template
from .models import Comment


class ContactCourse(forms.Form):
    name = forms.CharField(label='Nome', max_length=255)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )

    def send_mail(self, course):
        subject = '[%s] Contato' % course
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message']
        }
        template_name = 'courses/contact-email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

simplemooc/simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Course, Enrollment, Announcement, Lesson, Material
from .forms import ContactCourse, CommentForm
from .decorators import enrollment_required


def index(request):
    template_name = 'courses/index.html'
    courses = Course.objects.all()
    context = {'courses': courses}
    return render(request, template_name, context)


def details(request, slug):
    template_name = 'courses/details.html'
    course = get_object_or_404(Course, slug=slug)
    context = {}

    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course)
            form = ContactCourse()
    else:
        form = ContactCourse()

    context['course'] = course
    context['form'] = form
    return render(request, template_name, context)


@login_required
def enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, course=course
    )
    if created:
        enrollment.active()
        messages.success(request, 'Você foi inscrito no curso com sucesso')
    else:
        messages.info(request, 'Você já está inscrito no curso')
    return redirect('accounts:dashboard')


@login_required
def undo_enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(
        Enrollment, user=request.user, course=course
    )
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso')
        return redirect('accounts:dashboard')
    template_name = 'courses/undo-enrollment.html'
    context = {'enrollment': enrollment, 'course': course}
    return render(request, template_name, context)


@login_required
@enrollment_required
def announcements(request, slug):
    course = request.course
    template_name = 'courses/announcements.html'
    context = {
        'course': course,
        'announcements': course.announcements.all()
    }
    return render(request, template_name, context)


@login_required
@enrollment_required
def show_announcement(request, slug, pk):
    course = request.course
    announcement = get_object_or_404(course.announcements.all(), pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save()
        form = CommentForm()
        messages.success(request, 'Seu comentário foi enviado com sucesso')
    template_name = 'courses/show-announcement.html'
    context = {'course': course, 'announcement': announcement, 'form': form}
    return render(request, template_name, context)


@login_required
@enrollment_required
def lessons(request, slug):
    course = request.course
    template_name = 'courses/lessons.html'
    lessons = course.release_lessons()
    if request.user.is_staff:
        lessons = course.lessons.all()
    context = {'course': course, 'lessons': lessons}
    return render(request, template_name, context)


@login_required
@enrollment_required
def lesson(request, slug, pk):
    course = request.course
    template_name = 'courses/lesson.html'
    lesson = get_object_or_404(Lesson, pk=pk, course=course)
    print(lesson.is_available())
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta aula não está disponível')
        return redirect('courses:lessons', slug=course.slug)
    context = {'course': course, 'lesson': lesson}
    return render(request, template_name, context)


@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    material = get_object_or_404(
        Material, pk=pk, lesson__course=course
    )
    lesson = material.lesson
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Este material não está disponível')
        return redirect('courses:lesson', slug=course.slug, pk=lesson.pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template_name = 'courses/material.html'
    context = {
        'course': course, 'material': material, 'lesson': lesson
    }
    return render(request, template_name, context)

simplemooc/simplemooc/courses/templates/courses/announcement-mail.html
{{ announcement.content|linebreaks }}

simplemooc/simplemooc/courses/templates/courses/announcements.html
{% extends 'courses/course-dashboard.html' %}

{% block dashboard_content %}
    <div class="well">
        {% for announcement in announcements %}
        <h2>
            <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">
                {{ announcement.title }}
            </a>
        </h2>
        {{ announcement.content|linebreaks }}
        <p>
            <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}#comments">
                <i class="fa fa-comments-o"></i>
                {% with comments_count=announcement.comments.count %}
                    {{ comments_count }} Comentário{{ comments_count|pluralize }}
                {% endwith %}
            </a>
        </p>
        {% empty %}
            <h2>Nenhum anúncio criado</h2>
        {% endfor %}    
    </div>
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/contact-email.html
<p><strong>Nome:</strong> {{ name }}</p>
<p><strong>E-mail:</strong> {{ email }}</p>
{{ message|linebreaks }}

simplemooc/simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome:</strong> {{ name }}</p>
<p><strong>E-mail:</strong> {{ email }}</p>
{{ message|linebreaks }}

simplemooc/simplemooc/courses/templates/courses/course-dashboard.html
{% extends 'accounts/dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
{% endblock %}

{% block menu_options %}
    <li class="pure-menu-heading">
        {{ course }}
    </li>
    <li>
        <a href="{% url 'courses:lessons' course.slug %}">
            <i class="fa fa-video-camera"></i>
            Aulas e Materiais
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-info-circle"></i>
            Informações
        </a>
    </li>
    <li>
        <a href="{% url 'courses:announcements' course.slug %}">
            <i class="fa fa-envelope"></i>
            Anúncios
        </a>
    </li>
    <li>
        <a href="{% url 'threads:index' %}">
            <i class="fa fa-comments"></i>
            Fórum de Dúvidas
        </a>
    </li>
    {{ block.super }}
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">{{ course.name }}</h1>
                    <h2 class="splash-subhead">{{ course.description }}</h2>
                    <p>
                        <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="pure-g-r content-ribbon">
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Sobre o curso</h4>
                {{ course.about|linebreaks }}
            </div>
        </div>

        <div class="pure-u-1-3">
            <div class="l-box">
                {% if course.image %}
                    <img src="{{ course.image.url }}">
                {% else %}
                    <img src="{% static 'img/course-image.png' %}">
                {% endif %}

                <h4>Dúvidas?</h4>
                <p><a href="#contact" class="pure-button">Fale Conosco</a></p>
            </div>
        </div>
    </div>  

    <div class="pure-g-r content-ribbon" id="contact">
        <div class="pure-u-1">
            <h3>Tire suas dúvidas sobre o Curso</h3>

            {% if is_valid %}
                <p>Formulário enviado com sucesso!</p>
            {% endif %}
            
            <form action="." method="post" class="pure-form pure-form-aligned">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}                        
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">
                            Enviar
                        </button>
                    </div>
                </fieldset>      
            </form>
        </div>
    </div>
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
                <p>Abaixo a lista de cursos disponíveis na plataforma</p>
            </div>
        </div>
    </div>

    {% for course in courses %}
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <a href="{{ course.get_absolute_url }}">
                        {% if course.image %}
                            <img src="{{ course.image.url }}" alt="{{ course.name }}">
                        {% else %}
                            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}">
                        {% endif %}
                    </a>
                </div>
            </div>

            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">
                        <a href="{{ course.get_absolute_url }}">{{ course.name }}</a>
                    </h4>
                    {{ course.description|linebreaks }}
                </div>
            </div>
        </div>        

        {% empty %}

        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1">
                <div class="l-box">
                    <p>Nenhum curso disponível na plataforma</p>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/lesson.html
{% extends 'courses/course-dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block dashboard_content %}
	<div class="well">
		<h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
		{{ lesson.description|linebreaks }}
		<p>
			<h4>Materiais da aula</h4>
			<table class="pure-table full">
				<thead>
					<tr>
						<th>Nome</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
					{% for material in lesson.materials.all %}
						<tr class="{% cycle '' 'pure-table-odd' %}">
							<td>{{ material }}</td>
							<td>
								{% if material.is_embedded %}
									<a href="{% url 'courses:material' course.slug material.pk %}">
										<i class="fa fa-video-camera"> Acessar</i>
									</a>
								{% else %}
									<a href="{{ material.file.url }}" target="_blank">
										<i class="fa fa-download"> Baixar</i>
									</a>
								{% endif %}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</p>
	</div>
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/lessons.html
{% extends 'courses/course-dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
{% endblock %}

{% block dashboard_content %}
	{% for lesson in lessons %}
		<div class="well">
			<h2>
				<a href="{% url 'courses:lesson' course.slug lesson.pk %}">
					{{ lesson }}
				</a>
			</h2>
			<p>
				{{ lesson.description|truncatewords:'20' }}
				<br />
				<a href="{% url 'courses:lesson' course.slug lesson.pk %}">
					<i class="fa fa-eye"></i> Acessar aula
				</a>
			</p>
		</div>
	{% empty %}
		<div class="well">
			<h2>Nenhuma aula disponível.</h2>
		</div>
	{% endfor %}
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/material.html
{% extends 'courses/course-dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block dashboard_content %}
	<div class="well">
		<h2><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></h2>
		{{ material.embedded|safe }}
		<p>
			<a href="{% url 'courses:lesson' course.slug lesson.pk %}">Voltar</a>
		</p>
	</div>
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/show-announcement.html
{% extends 'courses/course-dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement.title }}</h2>
        {{ announcement.content|linebreaks }}
    </div>

    <div class="well">
        <h4 id="comments">
            Comentários
            <a href="" class="fright">Comentar</a>
        </h4>
        <hr />
        {% for comment in announcement.comments.all %}
            <p>
                <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
                {{ comment.comment|linebreaksbr }}
            </p>
        {% empty %}
            <p>Nenhum comentário para este anúncio.</p>
        {% endfor %}
        <form action="" method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/undo-enrollment.html
{% extends 'courses/course-dashboard.html' %}

{% block dashboard_content %}
    <form method="post" action="">
        {% csrf_token %}
        <h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Confirmar</button>
            <a href="{% url 'courses:announcements' course.slug %}" class="pure-button">Voltar</a>
        </div>
    </form>
{% endblock %}