simplemooc/simplemooc/core/urls.py
from django.conf.urls import url
from simplemooc.core import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contato/$', views.contact, name='contact'),
]

simplemooc/simplemooc/threads/urls.py
from django.conf.urls import url
from simplemooc.threads import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tag/(?P<tags>[\w_-]+)/$', views.index, name='index_tagged'),
    url(r'^respostas/(?P<pk>\d+)/correta/$', views.reply_correct, name='reply_correct'),
    url(r'^respostas/(?P<pk>\d+)/incorreta/$', views.reply_incorrect, name='reply_incorrect'),
    url(r'^(?P<slug>[\w_-]+)/$', views.thread, name='thread'),
]

simplemooc/simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^forum/', include('simplemooc.threads.urls', namespace='threads')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/threads/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.conf import settings


class Thread(models.Model):
    title = models.CharField('título', max_length=100)
    slug = models.SlugField('slug', max_length=100, unique=True)
    body = models.TextField('mensagem')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='autor', related_name='threads'
    )
    views = models.IntegerField('visualizações', blank=True, default=0)
    answers = models.IntegerField('respostas', blank=True, default=0)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)
    tags = TaggableManager()

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('threads:thread', (), {'slug': self.slug})

    class Meta:
        verbose_name = 'tópico'
        verbose_name_plural = 'tópicos'
        ordering = ['-updated_at']


class Reply(models.Model):
    reply = models.TextField('resposta')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='autor', related_name='replies'
    )
    thread = models.ForeignKey(Thread, verbose_name='tópico', related_name='replies')
    correct = models.BooleanField('correta?', blank=True, default=False)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)

    def __str__(self):
        return self.reply[:100]

    class Meta:
        verbose_name = 'resposta'
        verbose_name_plural = 'respostas'
        ordering = ['-correct', 'created_at']


def post_save_reply(created, instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()
    if instance.correct:
        instance.thread.replies.exclude(pk=instance.pk).update(correct=False)


def post_delete_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()


models.signals.post_save.connect(
    post_save_reply, sender=Reply, dispatch_uid='post_save_reply'
)
models.signals.post_delete.connect(
    post_delete_reply, sender=Reply, dispatch_uid='post_delete_reply'
)

simplemooc/simplemooc/threads/forms.py
from django import forms
from .models import Reply


class ReplyForm(forms.ModelForm):
	class Meta:
		model = Reply
		fields = ['reply']
			

simplemooc/simplemooc/threads/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, ListView, DetailView
from django.contrib import messages
from django.http import HttpResponse
from .models import Thread, Reply
from .forms import ReplyForm

#class ThreadView(View):
#    def get(self, request, *args, **kwargs):
#    	return render(request, 'threads/index.html')


class ThreadListView(ListView):
    paginate_by = 10
    template_name = 'threads/index.html'

    def get_queryset(self):
    	queryset = Thread.objects.all()
    	order = self.request.GET.get('order', '')
    	if order == 'views':
    		queryset = queryset.order_by('-views')
    	elif order == 'answers':
    		queryset = queryset.order_by('-answers')
    	tag = self.kwargs.get('tags', '')
    	if tag:
    		queryset = queryset.filter(tags__slug__icontains=tag)
    		print(queryset)
    	return queryset

    def get_context_data(self, **kwargs):
    	context = super(ThreadListView, self).get_context_data(**kwargs)
    	context['tags'] = Thread.tags.all()
    	return context


class ThreadDetailView(DetailView):
    model = Thread
    template_name = 'threads/thread.html'

    def get(self, request, *args, **kwargs):
        response = super(ThreadDetailView, self).get(request, *args, **kwargs)
        if not self.request.user.is_authenticated() or \
            (self.object.author != self.request.user):
            self.object.views = self.object.views + 1
            self.object.save()
        return response

    def get_context_data(self, **kwargs):
        context = super(ThreadDetailView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        context['form'] = ReplyForm(self.request.POST or None)
        return context

    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated():
            messages.error(
                self.request,
                'Para responder ao tópico é necessário estar logado.'
            )
            return redirect(self.request.path)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = context['form']
        if form.is_valid():
            reply = form.save(commit=False)
            reply.thread = self.object
            reply.author = self.request.user
            reply.save()
            messages.success(
                self.request, 'A sua resposta foi enviada com sucesso.'
            )
            context['form'] = ReplyForm()
        return self.render_to_response(context)


class ReplyCorrectView(View):
    correct = True

    def get(self, request, pk):
        reply = get_object_or_404(Reply, pk=pk, thread__author=request.user)
        reply.correct = self.correct
        reply.save()
        message = 'Resposta atualizada com sucesso'
        if request.is_ajax():
            data = {'sucess': True, 'message': message}
            return HttpResponse(json.dumps(data), mimetype='application/json')
        else:
            messages.success(request, message)
            return redirect(reply.thread.get_absolute_url())



index = ThreadListView.as_view()
thread = ThreadDetailView.as_view()
reply_correct = ReplyCorrectView.as_view()
reply_incorrect = ReplyCorrectView.as_view(correct=False)

simplemooc/simplemooc/threads/templates/threads/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
    	<div class="pure-u-1">
    		<ul class="breadcrumb">
    			<li><a href="{% url 'core:home' %}">Início</a></li>
    			<li>/</li>
    			<li><a href="{% url 'threads:index' %}">Fórum de Discussões</a></li>
    		</ul>
    	</div>

    	<div class="pure-u-1-3">
    		<div class="pure-menu pure-menu-open">
    			<ul>
    				<li class="pure-menu-heading">Tópicos do Fórum</li>
    				<li>
    					<a href="?order=recent">
    						<i class="fa fa-refresh"></i>
    						Mais Recentes
    					</a>
    				</li>
    				<li>
    					<a href="?order=views">
    						<i class="fa fa-eye"></i>
    						Mais Visualizados
    					</a>
    				</li>
    				<li>
    					<a href="?order=answers">
    						<i class="fa fa-comments"></i>
    						Mais Comentados
    					</a>
    				</li>
    				<li class="pure-menu-heading">Tags</li>
    				{% for tag in tags %}
	    				<li>
	    					<a href="{% url 'threads:index_tagged' tag.slug %}" class="tags">
	    						<i class="fa fa-tag"></i>
	    						{{ tag }}
	    					</a>
	    				</li>
	    			{% endfor %}
    			</ul>
    		</div>
    	</div>
    	<div class="pure-u-2-3">
    		<div class="inner">
    			{% for thread in object_list %}
	    			<div class="well">
	    				<h3>
	    					<a href="{{ thread.get_absolute_url }}" title="">{{ thread.title }}</a>
	    				</h3>
	    				<h5>
	    					Criado por {{ thread.author }} | {{ thread.answers }} resposta{{ thread.answers|pluralize }} | {{ thread.views }} visualizaç{{ thread.views|pluralize:"ão,ões" }}
	    				</h5>
	    				<p>
	    					<i class="fa fa-tags"></i>
	    					Tags: 
	    					{% for tag in thread.tags.all %}
	    						<a href="{% url 'threads:index_tagged' tag.slug %}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
	    					{% endfor %}
	    					<a href="{{ thread.get_absolute_url }}" class="fright" style="float: right;">Atualizado a {{ thread.updated_at|timesince }} atrás</a>
	    				</p>
	    			</div>
	    		{% endfor %}

	    		<ul class="pagination pagination-centered">
	    			{% if page_obj.has_previous %}
	    				<li>
	    					<a href="?page={{ page_obj.previous_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}">Anterior</a>
	    				</li>
	    			{% endif %}
		    		{% for page in paginator.page_range %}
			    		<li {% if page == page_obj.number %} class="active" {% endif %}>
			    			<a href="?page={{ page }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}">{{ page }}</a>
			    		</li>
		    		{% endfor %}
		    		{% if page_obj.has_next %}
	    				<li>
	    					<a href="?page={{ page_obj.next_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}">Próxima</a>
	    				</li>
	    			{% endif %}
		    	</ul>
    		</div>
    	</div>
    </div>
{% endblock %}

simplemooc/simplemooc/threads/templates/threads/thread.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <ul class="breadcrumb">
                <li><a href="{% url 'core:home' %}">Início</a></li>
                <li>/</li>
                <li><a href="{% url 'threads:index' %}">Fórum de Discussões</a></li>
                <li>/</li>
                <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
            </ul>
        </div>

        <div class="pure-u-1-3">
            <div class="pure-menu pure-menu-open">
                <ul>
                    <li class="pure-menu-heading">Tópicos do Fórum</li>
                    <li>
                        <a href="?order=recent">
                            <i class="fa fa-refresh"></i>
                            Mais Recentes
                        </a>
                    </li>
                    <li>
                        <a href="?order=views">
                            <i class="fa fa-eye"></i>
                            Mais Visualizados
                        </a>
                    </li>
                    <li>
                        <a href="?order=answers">
                            <i class="fa fa-comments"></i>
                            Mais Comentados
                        </a>
                    </li>
                    <li class="pure-menu-heading">Tags</li>
                    {% for tag in tags %}
                        <li>
                            <a href="{% url 'threads:index_tagged' tag.slug %}" class="tags">
                                <i class="fa fa-tag"></i>
                                {{ tag }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="inner">
                <div class="well">
                    <h2>{{ object }}</h2>
                    <p>{{ object.body|linebreaks }}</p>
                    <h5>Criado por {{ object.author }}</h5>
                    <p>
                        <i class="fa fa-tags"></i>
                        Tags: 
                        {% for tag in object.tags.all %}
                            <a href="{% url 'threads:index_tagged' tag.slug %}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                        {% endfor %}
                        <a href="{{ object.get_absolute_url }}" class="fright" style="float: right;">Criado a {{ object.created_at|timesince }} atrás</a>
                    </p>
                </div>
                <div class="well" id="div-comments">
                    <h4 id="comments">
                        Respostas
                        <a href="" class="fright">Responder</a>
                    </h4>
                    {% for reply in object.replies.all %}
                        <hr />
                        <p>                           
                            <strong>{{ reply.author }}</strong> disse à {{ reply.created_at|timesince }} atrás:<br />
                            {{ reply.reply|linebreaksbr }}
                            <br />
                            {% if object.author == user %}
                                <a href="{% url 'threads:reply_incorrect' reply.pk %}" class="pure-button button-error reply-cancel-correct-lnk {% if not reply.correct %} hidden {% endif %}">Cancelar resposta correta</a>
                                
                                <a href="{% url 'threads:reply_correct' reply.pk %}" class="pure-button button-success reply-correct-lnk {% if reply.correct %} hidden {% endif %}">Resposta Correta</a>

                                <span class="fright button-success reply-correct-msg {% if not reply.correct %} hidden {% endif %}">Resposta indicada pelo autor</span>
                                <br class="reply-correct-msg {% if not reply.correct %} hidden {% endif %}" />
                            {% elif reply.correct %}                                
                                <span class="fright button-success">Resposta indicada pelo autor</span>
                            {% endif %}
                        </p> 
                    {% endfor %}
                    <hr>
                    <form method="post" class="pure-form pure-form-stacked" id="add_comment">
                        <fieldset>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="pure-control-group">
                                    {{ field.label_tag }}
                                    {{ field }}
                                    {{ field.errors }}
                                </div>
                            {% endfor %}
                            <div class="pure-controls">
                                <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script type="text/javascript">
            $(".reply-cancel-correct-lnk").on("click", function(e){
                e.preventDefault();
                var $this = $(this);
                var $p = $this.closest("p")
                $.get($this.attr("href"), function(data){
                  if(data.success) {
                    $p.find(".reply-correct-msg").addClass("hidden");
                    $this.addClass("hidden");
                    $p.find(".reply-correct-lnk").removeClass("hidden");
                  } else{
                    alert(data.message)
                  }
                }, "json");
            });

            $(".reply-correct-lnk").on("click", function(e){
                e.preventDefault();
                var $this = $(this);
                var $p = $this.closest("p")
                $.get($this.attr("href"), function(data){
                  if(data.success) {
                    $("#div-comments .reply-correct-msg").addClass("hidden");
                    $("#div-comments .reply-cancel-correct-lnk").addClass("hidden");
                    $("#div-comments .reply-correct-lnk").removeClass("hidden");
                    
                    $p.find(".reply-correct-msg").removeClass("hidden");
                    $this.addClass("hidden");
                    $p.find(".reply-cancel-correct-lnk").removeClass("hidden");
                  } else{
                    alert(data.message)
                  }
                }, "json");
            })
        </script>
    {% endblock %}
{% endblock %}